apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/alexeykazakov-tenant/my-app/devfile-sample-go-basic@sha256:085c459c29ea874039d0db67c62dc4f09a9e86c5e1d2be54127d03b80e1bac50
        name: my-go
        resources: {}
status: {}
